-- GENERATED by `npm run db:bundle` from supabase/migrations/*.sql — do not edit by hand.
-- Paste this whole file into the Supabase SQL Editor and run it ONCE on a fresh project.
-- (Already ran the individual migrations? Don't run this again.)

-- ============================================================
-- 0001_schema.sql
-- ============================================================
-- Saved By Grace BJJ — core schema
-- Run in the Supabase SQL editor (or `supabase db push`). Safe to run once on a fresh project.

-- ---------------------------------------------------------------------------
-- Staff (coaches + admins who can log in to /admin and the future app)
-- ---------------------------------------------------------------------------
create table public.staff_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null default 'coach' check (role in ('admin', 'coach')),
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Coaches (public bio cards — separate from staff logins)
-- ---------------------------------------------------------------------------
create table public.coaches (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  bio text,
  belt_rank text,
  photo_url text,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Participants (students / members)
-- ---------------------------------------------------------------------------
create table public.participants (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  email text,
  phone text,
  date_joined date not null default current_date,
  -- Adult: white, blue, purple, brown, black. Youth: grey, yellow, orange, green.
  -- Coral / red are the senior black-belt degrees.
  belt_rank text not null default 'white' check (
    belt_rank in ('white', 'grey', 'yellow', 'orange', 'green', 'blue', 'purple', 'brown', 'black', 'coral', 'red')
  ),
  stripes int not null default 0 check (stripes between 0 and 10),
  program text[] not null default '{}' check (program <@ array['BJJ', 'Muay Thai', 'Kickboxing']),
  status text not null default 'active' check (status in ('active', 'inactive')),
  notes text,
  -- Storage object path inside the private `participant-photos` bucket (not a public URL).
  photo_url text,
  -- Secret used for QR self check-in. Never expose alongside other people's data.
  checkin_token uuid not null default gen_random_uuid() unique,
  created_at timestamptz not null default now()
);

create index participants_status_idx on public.participants (status);
create index participants_full_name_idx on public.participants (lower(full_name));

-- ---------------------------------------------------------------------------
-- Classes (weekly schedule)
-- ---------------------------------------------------------------------------
create table public.classes (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  day_of_week int not null check (day_of_week between 0 and 6), -- 0 = Sunday
  start_time time not null,
  end_time time not null,
  coach_id uuid references public.coaches(id) on delete set null,
  -- Muay Thai and Kickboxing are taught together in one session, so a class can serve both.
  program text not null check (program in ('BJJ', 'Muay Thai & Kickboxing', 'Muay Thai', 'Kickboxing')),
  check (end_time > start_time)
);

create index classes_day_idx on public.classes (day_of_week, start_time);

-- ---------------------------------------------------------------------------
-- Attendance (one row per participant per class session)
-- ---------------------------------------------------------------------------
create table public.attendance (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.participants(id) on delete cascade,
  -- restrict: deleting a class must never silently erase its attendance history
  class_id uuid not null references public.classes(id) on delete restrict,
  session_date date not null,
  checked_in_at timestamptz not null default now(),
  checked_in_by uuid references auth.users(id) on delete set null, -- null for QR self check-in
  check_in_method text not null default 'staff' check (check_in_method in ('staff', 'qr')),
  unique (participant_id, class_id, session_date)
);

create index attendance_session_idx on public.attendance (class_id, session_date);
create index attendance_participant_idx on public.attendance (participant_id, session_date desc);

-- ---------------------------------------------------------------------------
-- Progression log (belt / stripe history + coach notes)
-- ---------------------------------------------------------------------------
create table public.progression_log (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.participants(id) on delete cascade,
  entry_date date not null default current_date,
  belt_rank text check (
    belt_rank in ('white', 'grey', 'yellow', 'orange', 'green', 'blue', 'purple', 'brown', 'black', 'coral', 'red')
  ),
  stripes int check (stripes between 0 and 10),
  note text,
  -- Feedback the coach chose to send to the member. Private notes stay hidden from them;
  -- promotions (belt / stripes) are always visible to the member.
  visible_to_member boolean not null default false,
  logged_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  check (belt_rank is not null or stripes is not null or note is not null)
);

create index progression_participant_idx on public.progression_log (participant_id, entry_date desc);

-- A promotion entry (belt and/or stripes) updates the participant's current rank,
-- unless a later-dated promotion already exists (so back-filling history is safe).
create function public.apply_progression()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.belt_rank is null and new.stripes is null then
    return new;
  end if;

  if exists (
    select 1 from public.progression_log p
    where p.participant_id = new.participant_id
      and p.id <> new.id
      and (p.belt_rank is not null or p.stripes is not null)
      and p.entry_date > new.entry_date
  ) then
    return new;
  end if;

  update public.participants
  set belt_rank = coalesce(new.belt_rank, belt_rank),
      -- a new belt with no stripe value starts at 0 stripes
      stripes = coalesce(new.stripes, case when new.belt_rank is not null then 0 else stripes end)
  where id = new.participant_id;

  return new;
end;
$$;

create trigger progression_log_apply
after insert on public.progression_log
for each row execute function public.apply_progression();

-- ============================================================
-- 0002_rls.sql
-- ============================================================
-- Saved By Grace BJJ — Row Level Security, public views, storage
--
-- Access model
--   anon (public site)  : NO access to any table. Reads two curated views only
--                         (public_schedule, public_coaches).
--   coach               : read everything; insert participants (walk-ins), attendance,
--                         progression entries; delete attendance (undo a check-in).
--   admin               : everything a coach can do + manage participants, classes,
--                         coaches, staff profiles, and edit/delete progression entries.

-- ---------------------------------------------------------------------------
-- Role helpers (security definer so policies on staff_profiles don't recurse)
-- ---------------------------------------------------------------------------
create function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (select 1 from public.staff_profiles where user_id = (select auth.uid()));
$$;

create function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.staff_profiles
    where user_id = (select auth.uid()) and role = 'admin'
  );
$$;

revoke execute on function public.is_staff(), public.is_admin() from public, anon;
grant execute on function public.is_staff(), public.is_admin() to authenticated;
revoke execute on function public.apply_progression() from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Lock everything down, then open up explicitly
-- ---------------------------------------------------------------------------
revoke all on all tables in schema public from anon;

alter table public.staff_profiles enable row level security;
alter table public.coaches enable row level security;
alter table public.participants enable row level security;
alter table public.classes enable row level security;
alter table public.attendance enable row level security;
alter table public.progression_log enable row level security;

-- staff_profiles: you can read your own row (the app needs your role); admins manage all
create policy "staff_profiles read own or admin" on public.staff_profiles
  for select to authenticated
  using (user_id = (select auth.uid()) or public.is_admin());
create policy "staff_profiles admin insert" on public.staff_profiles
  for insert to authenticated with check (public.is_admin());
create policy "staff_profiles admin update" on public.staff_profiles
  for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "staff_profiles admin delete" on public.staff_profiles
  for delete to authenticated using (public.is_admin());

-- coaches
create policy "coaches staff read" on public.coaches
  for select to authenticated using (public.is_staff());
create policy "coaches admin insert" on public.coaches
  for insert to authenticated with check (public.is_admin());
create policy "coaches admin update" on public.coaches
  for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "coaches admin delete" on public.coaches
  for delete to authenticated using (public.is_admin());

-- classes
create policy "classes staff read" on public.classes
  for select to authenticated using (public.is_staff());
create policy "classes admin insert" on public.classes
  for insert to authenticated with check (public.is_admin());
create policy "classes admin update" on public.classes
  for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "classes admin delete" on public.classes
  for delete to authenticated using (public.is_admin());

-- participants (coaches may add walk-ins but only admins edit / delete)
create policy "participants staff read" on public.participants
  for select to authenticated using (public.is_staff());
create policy "participants staff insert" on public.participants
  for insert to authenticated with check (public.is_staff());
create policy "participants admin update" on public.participants
  for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "participants admin delete" on public.participants
  for delete to authenticated using (public.is_admin());

-- attendance
create policy "attendance staff read" on public.attendance
  for select to authenticated using (public.is_staff());
create policy "attendance staff insert" on public.attendance
  for insert to authenticated
  with check (public.is_staff() and checked_in_by = (select auth.uid()));
create policy "attendance staff delete" on public.attendance
  for delete to authenticated using (public.is_staff());

-- progression_log
create policy "progression staff read" on public.progression_log
  for select to authenticated using (public.is_staff());
create policy "progression staff insert" on public.progression_log
  for insert to authenticated
  with check (public.is_staff() and logged_by = (select auth.uid()));
create policy "progression admin update" on public.progression_log
  for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "progression admin delete" on public.progression_log
  for delete to authenticated using (public.is_admin());

-- ---------------------------------------------------------------------------
-- Public views (the ONLY thing the anon key can read)
-- Owned by postgres, so they bypass table RLS on purpose and expose only
-- non-sensitive columns.
-- ---------------------------------------------------------------------------
create view public.public_coaches with (security_invoker = false) as
  select id, full_name, bio, belt_rank, photo_url, sort_order
  from public.coaches;

create view public.public_schedule with (security_invoker = false) as
  select c.id, c.name, c.day_of_week, c.start_time, c.end_time, c.program,
         co.full_name as coach_name
  from public.classes c
  left join public.coaches co on co.id = c.coach_id;

grant select on public.public_coaches, public.public_schedule to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Storage
--   coach-photos       public bucket (shown on the website); admins upload
--   participant-photos private bucket (members may be minors); staff only, via signed URLs
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('coach-photos', 'coach-photos', true, 5242880, array['image/jpeg', 'image/png', 'image/webp']),
  ('participant-photos', 'participant-photos', false, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do nothing;

create policy "coach-photos staff read" on storage.objects
  for select to authenticated using (bucket_id = 'coach-photos' and public.is_staff());
create policy "coach-photos admin write" on storage.objects
  for insert to authenticated with check (bucket_id = 'coach-photos' and public.is_admin());
create policy "coach-photos admin update" on storage.objects
  for update to authenticated
  using (bucket_id = 'coach-photos' and public.is_admin())
  with check (bucket_id = 'coach-photos' and public.is_admin());
create policy "coach-photos admin delete" on storage.objects
  for delete to authenticated using (bucket_id = 'coach-photos' and public.is_admin());

create policy "participant-photos staff read" on storage.objects
  for select to authenticated using (bucket_id = 'participant-photos' and public.is_staff());
create policy "participant-photos staff write" on storage.objects
  for insert to authenticated with check (bucket_id = 'participant-photos' and public.is_staff());
create policy "participant-photos admin update" on storage.objects
  for update to authenticated
  using (bucket_id = 'participant-photos' and public.is_admin())
  with check (bucket_id = 'participant-photos' and public.is_admin());
create policy "participant-photos admin delete" on storage.objects
  for delete to authenticated using (bucket_id = 'participant-photos' and public.is_admin());

-- ============================================================
-- 0003_qr_checkin.sql
-- ============================================================
-- Saved By Grace BJJ — QR self check-in (personal link) — NOTE: the token-based
-- member_progress() defined at the bottom is replaced by login-based my_progress() in 0004.
--
-- Flow: each member has a secret personal link (participants.checkin_token), delivered
-- as a QR code from their profile. Opening it once stores the token on their phone.
-- A QR posted at the gym door then opens /checkin, which reads that stored token and
-- lets the member tap today's class. The same token opens the member's "My Progress"
-- page. These functions are the ONLY way the anon role can touch member data; the
-- secret token is the credential.

-- Today's date / time in the gym's timezone
create function public.gym_now()
returns timestamp
language sql
stable
set search_path = ''
as $$ select (now() at time zone 'Asia/Manila'); $$;

-- Returns null if the token is unknown or the member is inactive.
create function public.member_checkin_info(p_token uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_participant public.participants;
  v_now timestamp := public.gym_now();
  v_classes jsonb;
begin
  select * into v_participant from public.participants
  where checkin_token = p_token and status = 'active';
  if not found then
    return null;
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id', c.id,
    'name', c.name,
    'program', c.program,
    'start_time', c.start_time,
    'end_time', c.end_time,
    'coach_name', co.full_name,
    'open', v_now::time >= c.start_time - interval '60 minutes' and v_now::time <= c.end_time,
    'checked_in', exists (
      select 1 from public.attendance a
      where a.participant_id = v_participant.id
        and a.class_id = c.id
        and a.session_date = v_now::date
    )
  ) order by c.start_time), '[]'::jsonb)
  into v_classes
  from public.classes c
  left join public.coaches co on co.id = c.coach_id
  where c.day_of_week = extract(dow from v_now)::int;

  return jsonb_build_object('name', v_participant.full_name, 'classes', v_classes);
end;
$$;

-- status: ok | already | closed | invalid
create function public.member_check_in(p_token uuid, p_class_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_participant public.participants;
  v_class public.classes;
  v_now timestamp := public.gym_now();
  v_inserted int;
begin
  select * into v_participant from public.participants
  where checkin_token = p_token and status = 'active';
  if not found then
    return jsonb_build_object('status', 'invalid');
  end if;

  select * into v_class from public.classes where id = p_class_id;
  if not found
     or v_class.day_of_week <> extract(dow from v_now)::int
     or v_now::time < v_class.start_time - interval '60 minutes'
     or v_now::time > v_class.end_time then
    return jsonb_build_object('status', 'closed');
  end if;

  insert into public.attendance (participant_id, class_id, session_date, check_in_method)
  values (v_participant.id, v_class.id, v_now::date, 'qr')
  on conflict (participant_id, class_id, session_date) do nothing;
  get diagnostics v_inserted = row_count;

  return jsonb_build_object(
    'status', case when v_inserted = 1 then 'ok' else 'already' end,
    'name', v_participant.full_name
  );
end;
$$;

revoke execute on function public.member_checkin_info(uuid), public.member_check_in(uuid, uuid)
  from public;
grant execute on function public.member_checkin_info(uuid), public.member_check_in(uuid, uuid)
  to anon, authenticated;


-- ---------------------------------------------------------------------------
-- My Progress: what a member may see about themselves.
-- Returns null for an unknown / inactive token. Private coach notes are NOT returned:
-- a timeline entry is included only if it is a promotion or was marked "share with
-- member", and its note text is included only when shared.
-- ---------------------------------------------------------------------------
create function public.member_progress(p_token uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_p public.participants;
  v_today date := public.gym_now()::date;
begin
  select * into v_p from public.participants
  where checkin_token = p_token and status = 'active';
  if not found then
    return null;
  end if;

  return jsonb_build_object(
    'name', v_p.full_name,
    'belt_rank', v_p.belt_rank,
    'stripes', v_p.stripes,
    'date_joined', v_p.date_joined,
    'programs', to_jsonb(v_p.program),
    'today', v_today,
    'total_sessions', (
      select count(*) from public.attendance a where a.participant_id = v_p.id
    ),
    'sessions_30d', (
      select count(*) from public.attendance a
      where a.participant_id = v_p.id and a.session_date > v_today - 30
    ),
    'attendance_dates', coalesce((
      select jsonb_agg(a.session_date order by a.session_date)
      from public.attendance a
      where a.participant_id = v_p.id and a.session_date > v_today - 190
    ), '[]'::jsonb),
    'recent_sessions', coalesce((
      select jsonb_agg(
        jsonb_build_object('date', s.session_date, 'class_name', s.name)
        order by s.session_date desc, s.checked_in_at desc
      )
      from (
        select a.session_date, a.checked_in_at, c.name
        from public.attendance a
        join public.classes c on c.id = a.class_id
        where a.participant_id = v_p.id
        order by a.session_date desc, a.checked_in_at desc
        limit 20
      ) s
    ), '[]'::jsonb),
    'timeline', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'entry_date', e.entry_date,
          'belt_rank', e.belt_rank,
          'stripes', e.stripes,
          'feedback', e.visible_to_member,
          'note', case when e.visible_to_member then e.note end
        )
        order by e.entry_date desc, e.created_at desc
      )
      from (
        select * from public.progression_log l
        where l.participant_id = v_p.id
          and (l.belt_rank is not null or l.stripes is not null or l.visible_to_member)
        order by l.entry_date desc, l.created_at desc
        limit 100
      ) e
    ), '[]'::jsonb)
  );
end;
$$;

revoke execute on function public.member_progress(uuid) from public;
grant execute on function public.member_progress(uuid) to anon, authenticated;

-- ============================================================
-- 0004_member_accounts_and_limits.sql
-- ============================================================
-- Saved By Grace BJJ — member accounts, progress backend, SMS log, size guards
--
-- What this adds
--   * Members can have a login (username + password) and read ONLY their own progress,
--     through SECURITY DEFINER functions (never the tables directly, so coach-only notes
--     stay private).
--   * Profile settings a member can customise (nickname, goals, theme, accent colour).
--   * Counters + triggers that keep attendance totals current, and updated_at stamps.
--   * Indexes for every query the app runs (recent activity, search, foreign keys).
--   * An SMS log (for password-reset texts) that trims itself after 90 days.
--   * Size guards so the project stays under the 5 GB budget: length limits on text,
--     smaller photo limits, and functions to measure usage and find unused photos.
--
-- Replaces the token-based progress function from 0003 — progress now needs a login.

drop function if exists public.member_progress(uuid);

create extension if not exists pg_trgm with schema extensions;

-- ---------------------------------------------------------------------------
-- Generic updated_at trigger. Ignores counter-only changes so that an attendance
-- check-in does not look like the profile was edited.
-- ---------------------------------------------------------------------------
create function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if (to_jsonb(new) - 'updated_at' - 'total_sessions' - 'last_attended_on')
     is distinct from
     (to_jsonb(old) - 'updated_at' - 'total_sessions' - 'last_attended_on') then
    new.updated_at := now();
  end if;
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- participants: login link, attendance counters, updated_at, length limit
-- ---------------------------------------------------------------------------
alter table public.participants
  add column user_id uuid unique references auth.users(id) on delete set null,
  add column username text,
  add column total_sessions int not null default 0,
  add column last_attended_on date,
  add column updated_at timestamptz not null default now(),
  add constraint participants_username_format check (username is null or username ~ '^[a-z0-9._-]{3,30}$'),
  add constraint participants_notes_len check (notes is null or char_length(notes) <= 2000);

create unique index participants_username_key on public.participants (lower(username)) where username is not null;
-- Fast "%name%" search in the admin list
create index participants_name_trgm_idx on public.participants using gin (full_name extensions.gin_trgm_ops);
-- "Haven't been seen in a while" style queries
create index participants_last_attended_idx on public.participants (last_attended_on) where status = 'active';

create trigger participants_touch
before update on public.participants
for each row execute function public.touch_updated_at();

-- Backfill counters for any attendance that already exists
update public.participants p
set total_sessions = s.n, last_attended_on = s.d
from (
  select participant_id, count(*) as n, max(session_date) as d
  from public.attendance group by participant_id
) s
where s.participant_id = p.id;

-- Keep the counters current on every check-in / undo
create function public.attendance_counters()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    update public.participants
    set total_sessions = total_sessions + 1,
        last_attended_on = greatest(coalesce(last_attended_on, new.session_date), new.session_date)
    where id = new.participant_id;
  elsif tg_op = 'DELETE' then
    update public.participants
    set total_sessions = greatest(total_sessions - 1, 0),
        last_attended_on = (
          select max(a.session_date) from public.attendance a where a.participant_id = old.participant_id
        )
    where id = old.participant_id;
  end if;
  return null;
end;
$$;

create trigger attendance_counters_trg
after insert or delete on public.attendance
for each row execute function public.attendance_counters();

revoke execute on function public.attendance_counters() from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Promotion trigger, made independent of insert order.
-- Each field is applied only if no LATER entry supersedes it:
--   belt    <- a new belt, unless a later entry also sets a belt
--   stripes <- the new stripe count (or 0 for a new belt with none), unless a later
--              entry sets stripes or a belt
-- So back-filling history, or inserting several rows in one statement, always ends with
-- the participant on their most recent belt and stripe count.
-- ---------------------------------------------------------------------------
create or replace function public.apply_progression()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.belt_rank is not null and not exists (
    select 1 from public.progression_log p
    where p.participant_id = new.participant_id
      and p.id <> new.id
      and p.belt_rank is not null
      and (p.entry_date, p.created_at) > (new.entry_date, new.created_at)
  ) then
    update public.participants set belt_rank = new.belt_rank where id = new.participant_id;
  end if;

  if (new.belt_rank is not null or new.stripes is not null) and not exists (
    select 1 from public.progression_log p
    where p.participant_id = new.participant_id
      and p.id <> new.id
      and (p.belt_rank is not null or p.stripes is not null)
      and (p.entry_date, p.created_at) > (new.entry_date, new.created_at)
  ) then
    update public.participants set stripes = coalesce(new.stripes, 0) where id = new.participant_id;
  end if;

  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- progression_log: updated_at, length limit, indexes
-- ---------------------------------------------------------------------------
alter table public.progression_log
  add column updated_at timestamptz not null default now(),
  add constraint progression_note_len check (note is null or char_length(note) <= 2000);

create trigger progression_touch
before update on public.progression_log
for each row execute function public.touch_updated_at();

-- Dashboard "recent progress" and "recent check-ins"
create index progression_created_at_idx on public.progression_log (created_at desc);
create index attendance_checked_in_at_idx on public.attendance (checked_in_at desc);
-- Dashboard "check-ins today"
create index attendance_session_date_idx on public.attendance (session_date);
-- What a member may see: promotions + shared feedback only
create index progression_member_visible_idx
  on public.progression_log (participant_id, entry_date desc, created_at desc)
  where belt_rank is not null or stripes is not null or visible_to_member;

-- Foreign-key indexes (deletes and joins stay fast as data grows)
create index classes_coach_idx on public.classes (coach_id);
create index attendance_checked_in_by_idx on public.attendance (checked_in_by);
create index progression_logged_by_idx on public.progression_log (logged_by);

-- ---------------------------------------------------------------------------
-- Member settings (profile customisation). Members reach this only through the
-- my_* functions below; staff can read it.
-- ---------------------------------------------------------------------------
create table public.member_settings (
  participant_id uuid primary key references public.participants(id) on delete cascade,
  nickname text check (nickname is null or char_length(nickname) between 1 and 40),
  bio text check (bio is null or char_length(bio) <= 500),
  theme text not null default 'system' check (theme in ('system', 'light', 'dark')),
  accent text not null default 'red' check (accent in ('red', 'blue', 'mono')),
  -- true after an admin/coach resets the password: the member must choose their own
  must_change_password boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger member_settings_touch
before update on public.member_settings
for each row execute function public.touch_updated_at();

-- The public site has no access to any table: keep it that way for new tables too.
revoke all on public.member_settings from anon;
alter default privileges in schema public revoke all on tables from anon;

alter table public.member_settings enable row level security;
create policy "member_settings staff read" on public.member_settings
  for select to authenticated using (public.is_staff());

-- ---------------------------------------------------------------------------
-- staff_profiles: phone (for password-reset texts) + forced password change
-- ---------------------------------------------------------------------------
alter table public.staff_profiles
  add column phone text check (phone is null or char_length(phone) <= 20),
  add column must_change_password boolean not null default false,
  add column updated_at timestamptz not null default now();

create trigger staff_profiles_touch
before update on public.staff_profiles
for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- Member-facing functions. They identify the caller by auth.uid() and return only
-- what a member is allowed to see. Coach-only notes (participants.notes and private
-- progression notes) are never included.
-- ---------------------------------------------------------------------------
create function public.my_profile()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'participant_id', p.id,
    'full_name', p.full_name,
    'username', p.username,
    'nickname', s.nickname,
    'bio', s.bio,
    'phone', p.phone,
    'email', p.email,
    'theme', coalesce(s.theme, 'system'),
    'accent', coalesce(s.accent, 'red'),
    'belt_rank', p.belt_rank,
    'stripes', p.stripes,
    'photo_path', p.photo_url,
    'must_change_password', coalesce(s.must_change_password, false)
  )
  from public.participants p
  left join public.member_settings s on s.participant_id = p.id
  where p.user_id = (select auth.uid()) and p.status = 'active';
$$;

create function public.my_progress()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_p public.participants;
  v_today date := public.gym_now()::date;
begin
  select * into v_p from public.participants
  where user_id = (select auth.uid()) and status = 'active';
  if not found then
    return null;
  end if;

  return jsonb_build_object(
    'name', v_p.full_name,
    'belt_rank', v_p.belt_rank,
    'stripes', v_p.stripes,
    'date_joined', v_p.date_joined,
    'programs', to_jsonb(v_p.program),
    'today', v_today,
    'total_sessions', v_p.total_sessions,
    'sessions_30d', (
      select count(*) from public.attendance a
      where a.participant_id = v_p.id and a.session_date > v_today - 30
    ),
    'attendance_dates', coalesce((
      select jsonb_agg(a.session_date order by a.session_date)
      from public.attendance a
      where a.participant_id = v_p.id and a.session_date > v_today - 190
    ), '[]'::jsonb),
    'recent_sessions', coalesce((
      select jsonb_agg(
        jsonb_build_object('date', s.session_date, 'class_name', s.name)
        order by s.session_date desc, s.checked_in_at desc
      )
      from (
        select a.session_date, a.checked_in_at, c.name
        from public.attendance a
        join public.classes c on c.id = a.class_id
        where a.participant_id = v_p.id
        order by a.session_date desc, a.checked_in_at desc
        limit 20
      ) s
    ), '[]'::jsonb),
    'timeline', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'entry_date', e.entry_date,
          'belt_rank', e.belt_rank,
          'stripes', e.stripes,
          'feedback', e.visible_to_member,
          'note', case when e.visible_to_member then e.note end
        )
        order by e.entry_date desc, e.created_at desc
      )
      from (
        select * from public.progression_log l
        where l.participant_id = v_p.id
          and (l.belt_rank is not null or l.stripes is not null or l.visible_to_member)
        order by l.entry_date desc, l.created_at desc
        limit 100
      ) e
    ), '[]'::jsonb)
  );
end;
$$;

-- Members edit their own profile here. Length/format limits are enforced by the
-- table constraints, so bad input raises an error instead of being stored.
create function public.update_my_profile(
  p_nickname text,
  p_bio text,
  p_phone text,
  p_email text,
  p_theme text,
  p_accent text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id uuid;
begin
  select id into v_id from public.participants
  where user_id = (select auth.uid()) and status = 'active';
  if v_id is null then
    raise exception 'No member profile for this account' using errcode = '42501';
  end if;

  insert into public.member_settings (participant_id, nickname, bio, theme, accent)
  values (v_id, nullif(btrim(p_nickname), ''), nullif(btrim(p_bio), ''), p_theme, p_accent)
  on conflict (participant_id) do update
    set nickname = excluded.nickname,
        bio = excluded.bio,
        theme = excluded.theme,
        accent = excluded.accent;

  update public.participants
  set phone = nullif(btrim(p_phone), ''),
      email = nullif(btrim(p_email), '')
  where id = v_id;
end;
$$;

create function public.mark_password_changed()
returns void
language sql
security definer
set search_path = ''
as $$
  update public.member_settings s
  set must_change_password = false
  from public.participants p
  where p.id = s.participant_id and p.user_id = (select auth.uid());
$$;

revoke execute on function public.my_profile(), public.my_progress(),
  public.update_my_profile(text, text, text, text, text, text), public.mark_password_changed()
  from public, anon;
grant execute on function public.my_profile(), public.my_progress(),
  public.update_my_profile(text, text, text, text, text, text), public.mark_password_changed()
  to authenticated;

-- ---------------------------------------------------------------------------
-- SMS log (password-reset texts). Stores WHO/WHEN/outcome only — never the message
-- (it contains a temporary password) and only the last 4 digits of the number.
-- A statement trigger trims rows older than 90 days so it can never grow unbounded.
-- ---------------------------------------------------------------------------
create table public.sms_log (
  id uuid primary key default gen_random_uuid(),
  purpose text not null check (purpose in ('password_reset', 'account_created')),
  target_kind text not null check (target_kind in ('member', 'staff')),
  target_id uuid not null,
  phone_last4 text,
  provider text not null,
  status text not null check (status in ('sent', 'failed', 'manual')),
  error text check (error is null or char_length(error) <= 300),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index sms_log_target_idx on public.sms_log (target_id, created_at desc);
create index sms_log_created_idx on public.sms_log (created_at);
create index sms_log_created_by_idx on public.sms_log (created_by);

revoke all on public.sms_log from anon;
alter table public.sms_log enable row level security;
create policy "sms_log admin read" on public.sms_log
  for select to authenticated using (public.is_admin());

create function public.purge_old_sms_log()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.sms_log where created_at < now() - interval '90 days';
  return null;
end;
$$;

create trigger sms_log_purge
after insert on public.sms_log
for each statement execute function public.purge_old_sms_log();

revoke execute on function public.purge_old_sms_log() from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Size guards (keep the project under the 5 GB budget)
-- ---------------------------------------------------------------------------

-- Photos are compressed by the app before upload, so real files are small. This is a
-- hard ceiling in case anything bypasses the app.
update storage.buckets
set file_size_limit = 2097152
where id in ('coach-photos', 'participant-photos');

-- Total bytes used by the database + all stored files. Staff (and the server itself,
-- for member photo uploads) may call it; the app checks it before accepting a photo.
create function public.usage_bytes()
returns bigint
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_staff() and (select auth.role()) is distinct from 'service_role' then
    raise exception 'Not allowed' using errcode = '42501';
  end if;
  return pg_database_size(current_database())
    + coalesce((select sum((o.metadata ->> 'size')::bigint) from storage.objects o), 0);
end;
$$;

-- Admin-only breakdown for the Usage page.
create function public.usage_summary()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'Not allowed' using errcode = '42501';
  end if;

  return jsonb_build_object(
    'db_bytes', pg_database_size(current_database()),
    'storage_bytes', coalesce((select sum((o.metadata ->> 'size')::bigint) from storage.objects o), 0),
    'buckets', coalesce((
      select jsonb_agg(jsonb_build_object('bucket', b.bucket_id, 'files', b.files, 'bytes', b.bytes)
                       order by b.bytes desc)
      from (
        select o.bucket_id, count(*) as files, coalesce(sum((o.metadata ->> 'size')::bigint), 0) as bytes
        from storage.objects o group by o.bucket_id
      ) b
    ), '[]'::jsonb),
    'tables', coalesce((
      select jsonb_agg(jsonb_build_object('name', t.relname, 'bytes', t.bytes, 'rows', t.rows)
                       order by t.bytes desc)
      from (
        select c.relname,
               pg_total_relation_size(c.oid) as bytes,
               greatest(c.reltuples, 0)::bigint as rows
        from pg_class c
        join pg_namespace n on n.oid = c.relnamespace
        where n.nspname = 'public' and c.relkind = 'r'
      ) t
    ), '[]'::jsonb)
  );
end;
$$;

-- Photos nobody points at any more (left behind by replaced/removed photos).
-- Objects younger than an hour are ignored so an upload in progress is never touched.
create function public.orphaned_photos()
returns table (bucket_id text, name text, size bigint)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'Not allowed' using errcode = '42501';
  end if;

  return query
  select o.bucket_id, o.name, coalesce((o.metadata ->> 'size')::bigint, 0)
  from storage.objects o
  where o.created_at < now() - interval '1 hour'
    and (
      (o.bucket_id = 'participant-photos'
        and not exists (select 1 from public.participants p where p.photo_url = o.name))
      or
      (o.bucket_id = 'coach-photos'
        and not exists (select 1 from public.coaches c where c.photo_url like ('%/' || o.name)))
    );
end;
$$;

revoke execute on function public.usage_bytes(), public.usage_summary(), public.orphaned_photos()
  from public, anon;
grant execute on function public.usage_bytes(), public.usage_summary(), public.orphaned_photos()
  to authenticated;
